solve 0827
kyutech-programming-club/c_quiz_2021 pull request #33
Opened 2021-08-28 10:34 UTC by ailioolio

2021-08-28 16:51 UTC, take-cantik reviewed
動作としてはちゃんと実行できるんだけど、
これだと計算量がnumの階上分くらいあるからもう少し計算量少なくて済むようなやり方を考えてみて欲しい

2021-08-29 12:41 UTC, ailioolio commented
少しだけ計算量減ったと思うんですけどどうでしょうか

2021-08-30 01:48 UTC, take-cantik requested changes
今、全部割って行って割り切れたのが2個だったらっていう感じでやってると思うんだけど、
逆に言えば1とその数以外で割り切れたらだめっていう感じにできるのでそのやり方でやってみて
今のだと偶数の時2で割り切れてる時点で違うのに、最後の数まで回すのは意味ないよねみたいな感じ

2021-08-30 03:11 UTC, ailioolio commented
条件をつけ足してみました。自信あります！

2021-08-30 03:19 UTC, take-cantik commented on ailioolio/0827.c
> +        int sum = 2;
forの中で変数宣言するのは良くないかも
あとsumは2か2以外かっていう風でしか使われてないので、それだったら
is_primeみたいな変数使って0 or 1で表記する方がいいかな

でもやってることは合ってる

2021-08-30 03:45 UTC, ailioolio commented
変数宣言は全部一番上でしたほうがいいのでしょうか？

2021-08-30 08:22 UTC, take-cantik approved these changes
LGTMです
変数宣言のところあたりはまた調べてから共有しておきます

2021-08-30 08:34 UTC, merged