Chouette answered 0817 0818 0819
kyutech-programming-club/c_quiz_2021 pull request #5
Opened 2021-08-19 16:40 UTC by kei1115

2021-08-20 07:39 UTC, take-cantik requested changes
インデントが2と4とごちゃごちゃなってるから、そこを直した方がいいね
後、your_nameフォルダ消さんでほしかったw

2021-08-20 07:39 UTC, take-cantik commented on chouette/q_0817.c
> +  printf("%d", num + 1);
改行文字を入れて欲しいかな

2021-08-20 07:39 UTC, take-cantik commented on chouette/q_0818.c
> +  }
num % 2 の値が0なら0表示する
そうで無いなら1を表示するって意味になるから
もっといい感じにできるはずb

2021-08-20 07:48 UTC, kei1115 commented on chouette/q_0817.c
> +  printf("%d", num + 1);
直しました！

2021-08-20 07:48 UTC, kei1115 commented on chouette/q_0818.c
> +  }
直しました！

2021-08-20 07:52 UTC, take-cantik requested changes
テンプレのyour_name/を復活させて欲しい

2021-08-20 07:52 UTC, take-cantik commented on chouette/q_0818.c
> +  }
num % 2の値が0 or 1なら
if使わなくてもそのままって感じでできるはず

2021-08-20 17:13 UTC, kei1115 commented on chouette/q_0818.c
> +  }
なるほどです

2021-08-21 06:25 UTC, take-cantik approved these changes
確認できました
LGTM

2021-08-24 04:26 UTC, merged