answer 0821~0823
kyutech-programming-club/c_quiz_2021 pull request #68
Opened 2021-10-01 13:31 UTC by hibiki1228

gitignoreにwindows用の実行ファイルa.exeを除外するコードを追加しました～

2021-10-01 13:38 UTC, take-cantik requested changes
:memo:コメントしました

2021-10-01 13:38 UTC, take-cantik commented on hibiki/q0822.c
> +}
最後に空白行を追加してください

2021-10-01 14:33 UTC, hibiki1228 commented on hibiki/q0823.c
> +}
改行ないとdiffで変更してない最終行も表示されるんすね～
れびゅで赤くなるのは知ってたけど理由は初耳学認定です

2021-10-01 14:56 UTC, take-cantik commented
なんか違う
ダメです🙅‍♂️

2021-10-02 03:15 UTC, take-cantik approved these changes
🚀 LGTM

2021-10-02 06:38 UTC, merged